# Language
language: python

# Run with Python 3.
python:
  - "3.6"

# Email notifications
notifications:
  email: false

# Install dependencies
install:
  - easy_install distribute
  - pip3 install pytest-runner
  - pip3 install numpy
  - pip3 install pytest
  - pip3 install geopy
  - git clone https://github.com/Linuxbrew/brew.git ~/.linuxbrew
  - PATH="$HOME/.linuxbrew/bin:$PATH"
  - export MANPATH="$(brew --prefix)/share/man:$MANPATH"
  - export INFOPATH="$(brew --prefix)/share/info:$INFOPATH"
  - mkdir ~/glibc_install; cd ~/glibc_install 
  - wget http://ftp.gnu.org/gnu/glibc/glibc-2.23.tar.gz
  - tar zxvf glibc-2.23.tar.gz
  - cd glibc-2.23
  - mkdir build
  - cd build
  - ../configure --prefix=/opt/glibc-2.23
  - make -j4
  - make install
  - export LD_LIBRARY_PATH=/opt/glibc-2.23/lib
  - brew install mpich
  - pip3 install mpi4py

# Run pytests
script: pytest
