# Language
language: python

# Run with Python 3.
python:
  - "3.6"

# Email notifications
notifications:
  email: false

# Install dependencies
install:
  - easy_install distribute
  - pip3 install pytest-runner
  - pip3 install numpy
  - pip3 install pytest
  - pip3 install geopy
  - git clone https://github.com/Linuxbrew/brew.git ~/.linuxbrew
  - PATH="$HOME/.linuxbrew/bin:$PATH"
  - export MANPATH="$(brew --prefix)/share/man:$MANPATH"
  - export INFOPATH="$(brew --prefix)/share/info:$INFOPATH"
  - brew install mpich
  - sudo apt-get install libc6
  - pip3 install mpi4py

# Run pytests
script: pytest
