# This project has python as the main language
language: python

# Run things with Python 3.
python:
  - "3.6"

# Don't send email notifications for everything...
notifications:
  email: false

# We get a bare virtual machine
# We need to install our dependencies
install:
  - easy_install distribute
  - pip3 install pytest-runner
  - pip3 install numpy
  - pip3 install pytest
  - pip3 install geopy
  - brew install mpich
  - pip3 install mpi4py

# Run the tests
script: pytest
