# This project has python as the main language
language: python

# Run things with Python 3.
python:
  - "3.4"
  - "3.5"
  - "3.6"

# Don't send email notifications for everything...
notifications:
  email: false

# We get a bare virtual machine
# We need to install our dependencies
install:
  - easy_install distribute
  - pip install pytest-runner
  - pip install numpy
  - pip install pytest
  - pip install geopy
  - pip install https://bitbucket.org/mpi4py/mpi4py/downloads/mpi4py-3.0.0.tar.gz

# Run the tests
script: pytest
