# This project has python as the main language
language: python

# Run things with Python 3.
python:
  - "3.6"

# Don't send email notifications for everything...
notifications:
  email: false

# We get a bare virtual machine
# We need to install our dependencies
install:
  - easy_install distribute
  - pip3 install pytest-runner
  - pip3 install numpy
  - pip3 install pytest
  - pip3 install geopy
  - git clone https://github.com/Linuxbrew/brew.git ~/.linuxbrew
  - PATH="$HOME/.linuxbrew/bin:$PATH"
  - export MANPATH="$(brew --prefix)/share/man:$MANPATH"
  - export INFOPATH="$(brew --prefix)/share/info:$INFOPATH"
  - brew install mpich
  - apt-get install libc6
  - pip3 install mpi4py

# Run the tests
script: pytest
